services:
  # vue:
  #   build:
  #     context: ./frontend-vue
  #   container_name: vue_container
  #   ports:
  #     - "5001:5001"
  #   volumes:
  #     - ./vue:/app
  #     - /app/node_modules
  #   depends_on:
  #     - laravel
  #     - springboot
  #   command: >
  #     bash -c "npm install && npm run dev"

  # laravel:
  #   build:
  #     context: ./backend-laravel
  #   container_name: laravel_container
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./laravel:/app
  #     - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
  #   environment:
  #     - DB_CONNECTION=${DB_CONNECTION}
  #     - DB_HOST=${DB_HOST}
  #     - DB_PORT=${DB_PORT}
  #     - DB_DATABASE=${DB_DATABASE}
  #     - DB_USERNAME=${DB_USERNAME}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #   depends_on:
  #     - mysql
  #   command: >
  #     bash -c "chmod +x /usr/local/bin/wait-for-it.sh &&
  #              /usr/local/bin/wait-for-it.sh mysql 3306 ${DB_USERNAME} ${DB_PASSWORD} -- 
  #              php artisan key:generate &&
  #              php artisan migrate &&
  #              php artisan serve --host=0.0.0.0 --port=8000"

  springboot:
    build:
      context: ./backend-springboot
    container_name: springboot_container
    ports:
      - "8081:8081"
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/${DB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
      # - laravel
    command: >
      bash -c "chmod +x /usr/local/bin/wait-for-it.sh &&
               /usr/local/bin/wait-for-it.sh mysql 3306 ${DB_USERNAME} ${DB_PASSWORD} -- 
               /usr/local/bin/wait-for-it.sh laravel_container 8000 -- 
               java -jar app.jar"

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin_container
    platform: linux/amd64
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=${DB_HOST}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql

volumes:
  mysql_data: